<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return int
     */
    public function getNumberOfMeals()
    {
        return $this->createQueryBuilder('m')
            ->select('COUNT(m)')
            ->getQuery()
            ->getSingleScalarResult();

    }
}
