<?php

namespace AppBundle\Repository;

/**
 * OrderMealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderMealRepository extends \Doctrine\ORM\EntityRepository
{
}
