<?php

namespace AppBundle\Repository;

/**
 * OrderGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
