<?php

namespace AppBundle\Repository;

/**
 * OrderUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderUserRepository extends \Doctrine\ORM\EntityRepository
{
}
