<?php

namespace AppBundle\Repository;

/**
 * OrderMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
