<?php

namespace AppBundle\Repository;

/**
 * OrderGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumberOfOrdersPerDay($year, $month, $day)
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->where('YEAR(p.created_at) = :year')
            ->andWhere('MONTH(p.created_at) = :month')
            ->andWhere('DAY(p.created_at) = :day')
            ->setParameter('year', $year)
            ->setParameter('month', $month)
            ->setParameter('day', $day)
            ->getQuery()
            ->getSingleScalarResult();

    }
}
