<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Place;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return int
     */
    public function getNumberOfPlaces()
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @return Place|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLatestCreatedPlace()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.created_at', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return Place|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLatestModifiedPlace()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.modified_at', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
