<?php

namespace AppBundle\Provider;

class PlaceProvider extends \Faker\Provider\Base
{
  public function city()
  {
    return 'Bordeaux';
  }

  public function postcode()
  {
    return '33000';
  }

  public function country()
  {
    return 'France';
  }

  public function streetAddress()
  {
    $addresses = [
        '8 PLACE DE LA BOURSE',
        '51 RUE SAINTE CATHERINE',
        '12 RUE JOUANNET',
        '1 RUE DE CONDE',
        '29 QUAI DE LA MONNAIE',
        '9 RUE DABADIE',
        '17 RUE DES BAHUTIERS',
        '25 RUE BEYSSAC',
        '1 RUE DE LA SAU',
        '2 PLACE DU CHAPELET',
        '8 RUE LOUIS DE FOIX',
        '19 RUE DU PARLEMENT SAINT PIERRE',
        '41 RUE PERMENTADE',
        '19 RUE DU PALAIS DE L\'OMBRIERE',
        '1 RUE DE CREON',
        '1 RUE ESPRIT DES LOIS',
        '12 PLACE DE LA BOURSE',
        '13 COURS XAVIER ARNOZAN',
        '37 RUE SAUTEYRON',
        '28 RUE DE LA PREVOTE',
        '27 COURS XAVIER ARNOZAN',
        '1 RUE DE CANDALE',
        '5 RUE DE CREON',
        '12 PLACE DE LA BOURSE',
        '19 PLACE DE LA BOURSE',
        '2 COURS DE L\'INTENDANCE',
        '2 RUE DES LAURIERS',
        '38 RUE SAINT REMI',
        '1 RUE DE LA VILLE DE MIRMONT',
        '13 PLACE DU PARLEMENT',
        '16 RUE HUGLA',
        '44 RUE DAVID JOHNSTON',
        '12 RUE D\'ALEMBERT',
        '18 RUE DU PUITS DESCAZEAUX',
        '3 QUAI DE LA MONNAIE',
        '29 RUE DU CHAI DES FARINES',
        '24 RUE FERNAND PHILIPPART',
        '1 RUE GUERIN',
        '10 RUE DU QUAI BOURGEOIS',
        '1 PLACE DE LA BOURSE',
        '2 RUE ANDRE DUMERCQ',
        '1 RUE DE CREON',
        '25 RUE DU PARLEMENT SAINT PIERRE',
        '52 RUE NOTRE DAME',
        '36 RUE DES ARGENTIERS',
        '59 RUE CARPENTEYRE',
        '10 PLACE DE LA BOURSE',
        '6 RUE FENELON',
        '1 RUE DES REMPARTS',
        '11 RUE PORTE SAINT JEAN',
        '1 PLACE LUCIEN VICTOR MEUNIER',
        '1 RUE HUGLA',
        '1 PLACE DE LA COMEDIE',
        '23 RUE DU CHAI DES FARINES',
        '11 RUE JEAN JACQUES BEL',
        '2 PLACE DU CHAPELET',
        '24 RUE DE LA DEVISE',
        '1 RUE POQUELIN MOLIERE',
        '9 RUE DES TROIS CONILS',
        '2 RUE DES CORDELIERS',
        '8 RUE DU PUITS DESCUJOLS',
        '1 IMPASSE SAINT PIERRE',
        '24 RUE FERNAND PHILIPPART',
        '47 RUE DE LA ROUSSELLE',
        '2 RUE GENSAN',
        '10 PLACE DE LA BOURSE',
        '7 PLACE DU CHAMP DE MARS',
        '2 RUE LOUIS COMBES',
        '2 RUE DES ARGENTIERS',
        '25 RUE BUHAN',
        '3 RUE DE LA COQUILLE',
        '8 RUE JEAN JACQUES BEL',
        '17 RUE BOULAN',
        '22 RUE DES FAUSSETS',
        '29 RUE DU COUVENT',
        '1 PLACE LEON DUGUIT',
        '126 QUAI DES CHARTRONS',
        '17 RUE DU HAMEL',
        '20 RUE TUSTAL',
        '2 QUAI SAINTE CROIX',
        '5 PLACE JEAN JAURES',
        '46 RUE NEUVE',
        '1 RUE DE LA TOUR DU PIN',
        '1 PLACE DU PARLEMENT',
        '1 RUE GRAND RABBIN JOSEPH COHEN',
        '1 RUE VAUBAN',
        '12 RUE SAINT SERNIN',
        '2 RUE MICHEL MONTAIGNE',
        '6 RUE DU QUAI BOURGEOIS',
        '1 PLACE JEAN JAURES',
        '75 QUAI DES CHARTRONS',
        '1 PLACE LAINE',
        '2bis COURS XAVIER ARNOZAN',
        '43 RUE CONDILLAC',
        '24 IMPASSE MOULINIE',
        '10 RUE DE LA BOETIE',
        '5 PLACE DU PARLEMENT',
        '10 COURS DE GOURGUE',
        '1 IMPASSE BERTHUS',
        '2 RUE DE LA COQUILLE',
        '11 RUE COURBIN',
        '1 RUE DU HAMEL',
        '48 RUE LEYTEIRE',
        '82 RUE DES TROIS CONILS',
        '1 RUE PAUL BROCA',
        '9 COURS VICTOR HUGO',
        '10 RUE MATIGNON',
        '2 RUE DOCTEUR CHARLES NANCEL PENARD',
        '1 RUE DU CERF VOLANT',
        '1 PLACE DU PARLEMENT',
        '4 RUE GOBINEAU',
        '1 RUE CASTILLON',
        '1 PLACE DU PRADEAU',
        '103 COURS VICTOR HUGO',
        '36 RUE ANDRONNE',
        '1 QUAI DES CHARTRONS',
        '30 RUE CAMILLE SAUVAGEAU',
        '183 RUE SAINTE CATHERINE',
        '2 RUE PILET',
        '2 RUE BARADA',
        '2 RUE DU HA',
        '23 RUE DU SOLEIL',
        '9 RUE FERNAND PHILIPPART',
        '9 RUE DE LA MAISON DAURADE',
        '2 RUE CASTELNAU D\'AUROS',
        '23 RUE BUHAN',
        '17 QUAI LOUIS XVIII',
        '1 RUE DE MERIGNAC',
        '1 RUE DE LA TOUR DE GASSIES',
        '342 QUAI DE RICHELIEU',
        '34 QUAI DE LA MONNAIE',
        '62 PLACE TOURNY',
        '22 RUE TURENNE',
        '1 RUE GEORGES BONNAC',
        '17 PLACE MEYNARD',
        '283 RUE SAINTE CATHERINE',
        '284 RUE SAINTE CATHERINE',
        '2 RUE PORTE DES PORTANETS',
        '2 RUE POYENNE',
        '4 PLACE LEON DUGUIT',
        '3 PLACE SAINT PROJET',
        '41 RUE MONTBAZON',
        '1 RUE DES PONTETS',
        '18 RUE DU PROFESSEUR DEMONS',
        '1 RUE DE LA VILLE DE MIRMONT',
        '3 RUE BUFFON',
        '27 RUE TURENNE',
        '13 RUE DUDON',
        '15 RUE DES MENUTS',
        '34 RUE LABIRAT',
        ' RUE DE CALEMBERT',
        '1 RUE VANDEBRANDE',
        '74 COURS VICTOR HUGO',
        '24 RUE CAUSSEROUGE',
        '47 RUE DES BAHUTIERS',
        '73 RUE DE LA ROUSSELLE',
        '124 RUE DU PALAIS GALLIEN',
    ];

    return $addresses[array_rand($addresses)];
  }
}
